const state={visitors:null,passes:null,notifications:null,search:"",status:"all",type:"all",block:"all",guard:"all",vehicle:"all"};
const byId=(id)=>document.getElementById(id);
const esc=(v)=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
function toast(msg){const t=byId("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2200)}
function unique(v){return[...new Set(v)].sort()}
function opts(v,l){return[`<option value="all">${l}</option>`,...v.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`)].join("")}
function publicVisitors(){return state.visitors.visitors}
function themeFor(v){if(v.approvalStatus==="Pending")return"pending";if(v.approvalStatus==="Allowed")return"allowed";if(v.approvalStatus==="Rejected")return"rejected";if(v.approvalStatus==="No Response")return"noresponse";if(v.approvalStatus==="Checked Out")return"checkout";return v.theme}
function fillFilters(){const v=publicVisitors();byId("statusFilter").innerHTML=opts(unique(v.map(x=>x.approvalStatus)),"All Statuses");byId("typeFilter").innerHTML=opts(unique(v.map(x=>x.type)),"All Types");byId("blockFilter").innerHTML=opts(unique(v.map(x=>x.block)),"All Blocks");byId("guardFilter").innerHTML=opts(unique(v.map(x=>x.guard)),"All Guards")}
function filtered(){return publicVisitors().filter(v=>{const txt=JSON.stringify(v).toLowerCase();return(!state.search||txt.includes(state.search))&&(state.status==="all"||v.approvalStatus===state.status)&&(state.type==="all"||v.type===state.type)&&(state.block==="all"||v.block===state.block)&&(state.guard==="all"||v.guard===state.guard)&&(state.vehicle==="all"||v.vehicleAvailable===state.vehicle)})}
function renderSummary(){const v=publicVisitors();const rows=[["Visitors Today",v.length,"checkout"],["Pending Approval",v.filter(x=>x.approvalStatus==="Pending").length,"pending"],["Allowed Visitors",v.filter(x=>x.approvalStatus==="Allowed").length,"allowed"],["Rejected Visitors",v.filter(x=>x.approvalStatus==="Rejected").length,"rejected"],["Deliveries Today",v.filter(x=>x.type==="Delivery").length,"delivery"],["Workers/Vendors Today",v.filter(x=>["Worker","Vendor"].includes(x.type)).length,"worker"],["Vehicles Entered",v.filter(x=>x.vehicleAvailable==="Yes").length,"checkout"],["Active Gate Passes",state.passes.passes.filter(p=>p.status==="Active").length,"allowed"],["Checked Out Visitors",v.filter(x=>x.approvalStatus==="Checked Out"||x.exitTime!=="-").length,"checkout"]];byId("summaryCards").innerHTML=rows.map(([l,val,th])=>`<article class="summary-card ${th}" style="--accent:var(--${th})"><strong>${esc(l)}</strong><span>${val}</span></article>`).join("")}
function renderVisitors(){const rows=filtered();byId("visitorCount").textContent=`${rows.length} visitors`;byId("visitorCards").innerHTML=rows.map(v=>`<article class="visitor-card ${themeFor(v)}"><div class="card-top"><span class="visitor-icon">${esc(v.type.slice(0,3).toUpperCase())}</span><span class="status-badge">${esc(v.approvalStatus)}</span></div><h3>${esc(v.name)}</h3><p>${esc(v.purpose)}</p><div class="visitor-meta"><span><strong>${esc(v.block)}-${esc(v.house)}</strong>Visiting House</span><span><strong>${esc(v.entryTime)}</strong>Entry</span><span><strong>${esc(v.exitTime)}</strong>Exit</span></div><div class="badge-row"><span class="mini-badge">${esc(v.type)}</span><span class="mini-badge">${esc(v.guard)}</span><span class="mini-badge">${esc(v.vehicleMasked)}</span></div><button class="details-button" type="button" data-visitor-id="${v.id}">View Details</button></article>`).join("")}
function renderPasses(){byId("gatePassCards").innerHTML=state.passes.passes.map(p=>`<article class="pass-card ${p.status==="Active"?"allowed":"checkout"}"><span class="status-badge">${esc(p.status)}</span><h3>${esc(p.pass)}</h3><p>${esc(p.visitorName)} / ${esc(p.house)}</p><p>${esc(p.purpose)}</p><p>${esc(p.validFrom)} to ${esc(p.validTill)}</p><p>Issued by ${esc(p.issuedBy)} / ${esc(p.approvalStatus)}</p></article>`).join("")}
function renderReports(){const reps=["Daily visitor report","Monthly visitor report","Delivery report","Worker/vendor entry report","Vehicle entry report","Pending approval report","Guard-wise entry report"];byId("reportCards").innerHTML=reps.map(r=>`<article class="pass-card checkout"><h3>${r}</h3><p>Static report placeholder generated from visitor JSON.</p><button type="button" class="details-button" data-action="Generate ${r}">Generate</button></article>`).join("")}
function openVisitor(id){const v=publicVisitors().find(x=>x.id===id);const notes=state.notifications.notifications.filter(n=>n.visitorId===id);byId("modalContent").innerHTML=`<div class="modal-body ${themeFor(v)}"><div class="modal-hero"><p class="eyebrow">${esc(v.type)}</p><h2 id="modalTitle">${esc(v.name)}</h2><p>Public view keeps mobile, vehicle and ID proof details masked.</p></div><div class="detail-grid"><div><strong>Mobile</strong><br>${esc(v.mobileMasked)}</div><div><strong>Vehicle</strong><br>${esc(v.vehicleMasked)}</div><div><strong>ID Proof</strong><br>${esc(v.idProofMasked)}</div><div><strong>House</strong><br>${esc(v.block)}-${esc(v.house)}</div><div><strong>Resident</strong><br>${esc(v.resident)}</div><div><strong>Approval</strong><br>${esc(v.approvalStatus)}</div><div><strong>Entry/Exit</strong><br>${esc(v.entryTime)} / ${esc(v.exitTime)}</div><div><strong>Guard</strong><br>${esc(v.guard)}</div><div><strong>Valid Till</strong><br>${esc(v.validTill)}</div></div><div class="detail-panel"><h3>Approval Timeline</h3><p>Request created at ${esc(v.entryTime)}. Resident approval time: ${esc(v.residentApprovalTime)}.</p></div><div class="detail-panel"><h3>Notification Status</h3><p>${notes.map(n=>`${n.channel}: ${n.status} (${n.time})`).join("<br>")||"No notifications recorded."}</p></div><div class="detail-panel"><h3>Gate Pass Status</h3><p>${esc(v.validTill)}</p></div><div class="modal-actions"><button type="button" data-action="Admin allow visitor">Allow</button><button type="button" data-action="Admin reject visitor">Reject</button><button type="button" data-action="Update exit time">Update Exit</button><button type="button" data-action="Send WhatsApp/SMS placeholder">Notify Resident</button></div></div>`;const m=byId("visitorModal");if(typeof m.showModal==="function")m.showModal();else m.setAttribute("open","")}
function setup(){byId("lastUpdated").textContent=`Updated ${state.visitors.lastUpdated}`;["searchInput","statusFilter","typeFilter","blockFilter","guardFilter","vehicleFilter"].forEach(id=>byId(id).addEventListener(id==="searchInput"?"input":"change",e=>{const map={searchInput:"search",statusFilter:"status",typeFilter:"type",blockFilter:"block",guardFilter:"guard",vehicleFilter:"vehicle"};state[map[id]]=id==="searchInput"?e.target.value.trim().toLowerCase():e.target.value;renderVisitors()}));byId("visitorCards").addEventListener("click",e=>{const b=e.target.closest("[data-visitor-id]");if(b)openVisitor(b.dataset.visitorId)});document.addEventListener("click",e=>{const a=e.target.closest("[data-action]");if(a)toast(`${a.dataset.action}: placeholder only.`)});byId("themeToggle").addEventListener("click",()=>{document.body.classList.toggle("dark");localStorage.setItem("ibpVisitorTheme",document.body.classList.contains("dark")?"dark":"light")});if(localStorage.getItem("ibpVisitorTheme")==="dark")document.body.classList.add("dark")}
async function init(){const[v,p,n]=await Promise.all([fetch("data/visitor-records.json"),fetch("data/gate-passes.json"),fetch("data/visitor-notifications.json")]);state.visitors=await v.json();state.passes=await p.json();state.notifications=await n.json();fillFilters();setup();renderSummary();renderVisitors();renderPasses();renderReports()}
init().catch(e=>document.body.insertAdjacentHTML("afterbegin",`<div class="access-strip">Unable to load visitor data: ${esc(e.message)}</div>`));
